services:
    app:
        image: naru-backend
        container_name: naru-backend
        build: .
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: docker
        volumes:
            - .:/app # 현재 디렉토리를 /app으로 연결
        working_dir: /app # 컨테이너의 작업 디렉토리를 /app으로 설정
        command: ["java", "-jar", "/opt/app/app.jar"] # JAR 파일 실행
        networks:
            - naru-net

networks:
    naru-net:
        external: true
