services:
    app:
        image: dmdmdm1322/naru-backend-prod
        container_name: naru-backend
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: prod
        networks:
            - naru-net

networks:
    naru-net:
        external: true
