services:
    app:
        image: dmdmdm1322/naru-backend-prod
        container_name: naru-backend
        # build:
        #     context: .
        #     dockerfile: Dockerfile.prod
        ports:
            - "8080:8080"
        # environment:
        #     SPRING_PROFILES_ACTIVE: prod
        networks:
            - naru-net

networks:
    naru-net:
        external: true
