services:
    app:
        image: naru-backend
        container_name: naru-backend
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: docker
        networks:
            - naru-net

networks:
    naru-net:
        external: true
