name: Deploy to Oracle Instance

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Setup SSH agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build --no-cache -f Dockerfile.prod -t dmdmdm1322/naru-backend-prod:latest .

            - name: Push Docker image to Docker Hub
              run: |
                  docker push dmdmdm1322/naru-backend-prod:latest

            # - name: Setup SSH agent
            #   uses: webfactory/ssh-agent@v0.5.3
            #   with:
            #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Run docker-compose on Oracle instance
              run: |
                  ssh -o StrictHostKeyChecking=no opc@144.24.94.9 "cd ~/workspace/backend-naru && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up --build -d"
