name: Deploy to Oracle Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run docker-compose on Oracle instance
      run: |
        ssh -o StrictHostKeyChecking=no opc@144.24.94.9 "cd ~/workspace/backend-naru && docker-compose -f docker-compose.prod.yml up --build -d"
